---
title: "Omrane"
---

L'installation des packages nécessaires
```{r}
install.packages("ggcorrplot")
```

Le chargement des librairies nécessaire

```{r}
# Manipulation
library(dplyr)
library(tidyverse)
library(caTools)
library(lubridate)

# Visualization
library(ggplot2)
library(plotly)
library(ggthemes)
library(corrplot)
library(ggcorrplot)
library(ggstatsplot)
library(ggpubr)

# EDA REPORT
library(dlookr)
library(visdat)
library(DataExplorer)
library(SmartEDA)
library(flextable)
library(ISLR)


# Machine Learning
library(missRanger)
library(rpart)
library(randomForest)
library(Amelia)
library(psych)
library(caret)
library(Hmisc)

```

```{r}
# Importer les donnée qui ont dans le fichier Omrane.csv qui est dans la même répertoire
data <- read.csv(file = "./Omrane.csv", header = TRUE, sep="\t", dec=",")
#data$X <- NULL
# les premières observations des données
head(data, n=3)

# les dernières observations des données
tail(data)


print(paste("Nombre d'observations",nrow(data) , sep = " "))
print(paste("Nombre de colonnes:",ncol(data)  , sep = " "))

# La structure des attributs
str(data)

# Statiques de bases sur l'ensemble des attributs
summary(data)
describe(data)

# Les valeurs non-observés pour chaque attribut
missmap(data)
```


Pre-Processing, correction et nettoyage des données

```{r}
# deleting the columns that we don't need in our analysis
data = select(data, c(-"N..Lot",-"TitreFoncier",-"CIN.RC",-"DateDeCréation","S"))
colnames(data)[16] <- "DésignationTypeDeDocument"
# generer une liste des indexes aléatoires
shuffle_index <- sample(1:nrow(data))

# On va utiliser ses indexes pour mélanger les donnée
data <- data[shuffle_index, ]
glimpse(data)


#fixing the column type
cols.num <- c("NombreUnité","StatutADV", "Superficie", "PrixUnitaire", "PrixTotal", "Vers1", "Vers2", "Vers3", "TotalVersement",
               "VersRegularis","TropPerçuRéglé", "TropPerçuNonRéglé", "ResteàPayer", "TotalAvances")
cols.char = c("NuméroClient")
cols.date = c("DateLivraison","DateContrat","DateDeCréation")
data[cols.num] <- sapply(data[cols.num],as.numeric)
data[cols.char] <- sapply(data[cols.char],as.character)
data$Création <- ymd(data$Création)
data$DateContrat <- ymd(data$DateContrat)
data$DateLivraison <- ymd(data$DateLivraison)


sapply(data, class)
```


L'imputation des valeurs manquantes
```{r}
# Les valeurs non-observés pour chaque attribut
data %>% plot_missing()
# since the two columns DateContrat and DateLivraison are 100% missing and the company can't provide a new dataset that fix the problem of the missing Feautures unless they are very important and less than 50% in the case we could use them in Analysis in our case the mentioned variables should be dropped
plot_na_pareto(data, only_na = TRUE)
ggplotly(plot_na_pareto(data,  only_na = TRUE))
# the problem with pareto chart is that we don't know whether the missing values in different columns belong to the same row of observations

# so visualize the missing values across columns
plot_na_intersect(data)
#vis_miss(data) %>% ggplotly()

#to reduce bias we remove the two variables
data = select(data, c(-"DateLivraison",-"DateContrat"))

# to impute the numeric continueous missing values & outliers we're going to use machine learning algorithms :
# rpart - Recursive Partitioning and Regression Trees.
# mice - Multivariate Imputation by Chained Equations
# mean
# dlookr imputation
#set.seed(123)
#data_na <- generateNA(data) %>% mutate(Designation = factor(Designation))
#plot_na_intersect(data_na, only_na = TRUE)
#
#imputate_na(data_na, Création, StatutADV, method = "mean") %>% 
#  plot()
#imputate_na(data_na, Création, StatutADV, method = "rpart") %>% plot()
#imputate_na(data_na, Création, StatutADV, method = "mice", seed = 111) %>% plot()
#
#Miss Ranger Imputation
#data_imputed <- missRanger(data_na, formula = . ~ ., num.trees = 1000, seed = 3)
```

EDA Explatory Data Analysis with DataExplorer
```{r}
# EDA with 

config <- configure_report(
  #add_plot_str = FALSE,
  #add_plot_qq = FALSE,
  add_plot_prcomp = FALSE,
  add_plot_density = TRUE,
  #add_plot_boxplot = FALSE,
  #add_plot_scatterplot = FALSE,
  global_ggtheme = quote(theme_minimal(base_size = 14))
)

data %>% create_report(
  output_file = "Omrane_DataExplorerEDA",
  #y="Description",
  report_title = "EDA Report - Omrane Population",
  config = config
)

?create_report

sample %>% create_report(
  output_file = "Omrane_Sample_Report",
  #y="Description",
  report_title = "EDA Report - Omrane Sample",
  config = config
)



# 2.0 Data Introduction
data %>% introduce()
data %>% plot_intro()



# 3.0 Missing Values
data %>% plot_missing()
data %>% profile_missing()




# 4.0 Continuous Features
data %>% plot_density()
data %>% plot_histogram()
# Explore Numeric Variable Via Descriptive Statistics
dlookr::describe(data) %>% flextable()

data %>%
    group_by(Description) %>%
    univar_numeric(TotalAvances)

data %>%
  #group_by(Description) %>%
  diagnose_numeric() %>%
  flextable()




# 5.0 Categorical Features (Explore Categorical Variables with Fisher's & Chi-Square
data %>% plot_bar()
plot_bar(data, by = "Description")



# 6.0 Relationship non-parametric Kendall OR spearman
ggplotly(plot_correlation(data))
#cor.ci(data, method="spearman")
ggcorrmat(data=data, output="dataframe")


# Normality Diagnosis
plot_qq(data)
plot_qq(data, by="Description")
#ggqqplot(data, "Superficie", facet.by = "Description")


d = ggbetweenstats(data = data, x = Description, y = TotalAvances, type= "np")
ggplotly(d)
```

EDA with SmartEDA
```{r}
ExpReport(
     data, 
     op_file="Omrane_SmartEDA.html", 
     op_dir = tempdir()
  )
?ExpReport
```

EDA with dlookr
```{r eval=F}
eda_report(
      data,  
      target = "Description", 
      output_format = "html",
      output_file = "Omrane_dlookrEDA.html",
      output_dir = ".",
    )
?eda_report
```




```{r}
#Echantiollonage
#set.seed(2) #2 représente 20% de chaque groupe
#n = 700 
#sample= data[sample(1:nrow(data),n), ]

# 7 -> 10

library(shiny)
data.ml = select(data, c(-"Opération",-"Division",-"Client",-"NombreUnité",-"TypeDocument",
                         -"VersRegularis",-"TropPerçuRéglé", -"TropPerçuNonRéglé",-"TotalAvances",-"Dossier",-"NuméroClient",
                         -"Vers1",-"Vers2",-"Vers3",-"TotalVersement",-"DésignationTypeDeDocument"))
data.ml = select(data.ml,c(-"DésignationTypeDeDocument"))


summary(data.ml)

```
